apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    name: test
  annotations:
    iam.amazonaws.com/permitted: ".*"
---
apiVersion: v1
kind: Pod
metadata:
  name: tomcat7
  namespace: test
  annotations:
    iam.amazonaws.com/role:  app_role
spec:
  containers:
    - image: tomcat:7
      imagePullPolicy: Always
      name:  tomcat7
  nodeSelector:
    kubernetes.io/role: node
